/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Water": "水",
    "Welcome to the Cosmic Forge!": "欢迎来到 宇宙熔炉！",
    "Welcome Pioneer! Please enter your code name!": "欢迎先锋! 请输入你的代号(英文数字名称)！",
    "Visual": "视觉",
    "You can load a previous game by changing this name to a previous one.": "您可以通过将此名称更改为以前的游戏名称，来加载以前的游戏进度。",
    "CONFIRM": "确认",
    "Contact": "联系",
    "Discover": "发现",
    "Energy:": "能量:",
    "No saved game data found.": "没有找到保存的游戏数据。",
    "Start game full screen": "全屏开始游戏",
    "START": "开始",
    "Star Ship": "星船",
    "Star Map": "星图",
    "Star Data": "星星数据",
    "STANDARD CANCEL": "标准取消",
    "STANDARD CONFIRM": "标准确认",
    "Steel": "钢",
    "Story": "故事",
    "Study a Star": "研究星星",
    "Tech Tree": "科技树",
    "Titanium": "钛",
    "Technology": "科技",
    "Unlock": "解锁",
    "Unlock All Tabs": "解锁全部标签页",
    "Variable Debugger": "变量调试器",
    "With each click, fusion, and discovery, you edge closer to fulfilling your destiny!": "随着每一次点击、融合和发现，你离实现自己的命运更近了一步！",
    "You find yourself with advanced knowledge but on a world with almost no material!": "你发现自己拥有先进的知识，但在一个几乎没有材料的世界！",
    "Begin by gathering Hydrogen and mastering the art of fusion to create Helium, Carbon, and beyond.": "从收集氢开始，掌握聚变的艺术来创造氦、碳和其他。",
    "Build Launch Pad, Scanner & All Rockets": "建造发射台，扫描仪和所有火箭",
    "Cash:": "现金:",
    "Clear All": "清除全部",
    "Energy": "能量",
    "Gain": "获取",
    "Get Started": "开始",
    "Good Luck!": "祝你好运!",
    "Helium": "氦",
    "Grant All Techs": "授予所有科技",
    "Grant": "授予",
    "Here you can gain and sell resources. You can also upgrade your storage capacity and automate resource harvesting.  When you discover fusion, you will also handle that here.": "在这里你可以获得和出售资源。您还可以升级存储容量并自动获取资源。当你发现核聚变时，你也会在这里处理它。",
    "Hydrogen": "氢",
    "Iron": "铁",
    "Mining": "采矿",
    "Oxygen": "氧",
    "Power": "电力",
    "Power On": "电力启动",
    "Power Plant": "发电厂",
    "Saving / Loading": "保存 / 加载",
    "Silicon": "硅",
    "Rocket": "火箭",
    "Research": "研究",
    "Resources": "资源",
    "Rebirth": "重生",
    "Powered:": "电力:",
    "Auto Save:": "自动保存:",
    "Explore new technologies to unlock powerful compounds, and one by one recreate the materials to create": "探索新技术来解锁强大的化合物，并一个接一个地重新创建要创建的材料",
    "a craft to explore and discover the secrets of the interstellar medium!": "一艘探索和发现星际介质秘密的飞船！",
    "Advanced Power Plant": "高级发电厂",
    "Antimatter:": "反物质:",
    "Battery:": "电池:",
    "Carbon": "碳",
    "Colonise": "殖民",
    "Asteroids": "小行星",
    "Ascendency": "优势",
    "Build": "建造",
    "Space Telescope": "太空望远镜",
    "!!!RESET ALL GAME PROGRESS FOR THIS PIONEER NAME!!!": "!!!重置这个先锋名称相关的所有游戏进度!!!",
    "Change the game settings to your liking.": "根据你的喜好改变游戏设置。",
    "Export File": "导出文件",
    "Import File": "导入文件",
    "Import Save:": "导入存档:",
    "Export Save:": "导出存档:",
    "Export Cloud Save:": "导出云存档:",
    "Import Cloud Save:": "导入云存档:",
    "Export Cloud Save": "导出云存档",
    "Import Cloud Save": "导入云存档",
    "Energy Storage": "能量存储",
    "Debug Window": "调试窗口",
    "Glass": "玻璃",
    "HARD RESET:": "硬重置:",
    "Heavy Rain!": "大雨!",
    "Space Mining": "太空采矿",
    "Save and Load your progress in the game.": "在游戏中保存并加载你的进度。",
    "Launch Pad": "发射台",
    "Interstellar": "星际穿越",
    "Liquids": "液体",
    "Solids": "固体",
    "Solar Power Plant": "太阳能发电厂",
    "Sodium": "钠",
    "Philosophy": "哲学",
    "Philosophies": "Philosophies",
    "NO": "不",
    "Game Options": "游戏选项",
    "Galactic Market": "银河市场",
    "Galactic": "银河",
    "Antimatter Engines:": "反物质引擎:",
    "Atmospheric Telescopes, Rocket Composites, Quantum Computing": "大气望远镜，火箭复合材料，量子计算",
    "Build a Science Lab to do large amounts of Research - Power: 50KW / s": "建立一个科学实验室进行大量的研究 - 功率：50KW / 秒",
    "Here you can buy upgrades to generate research points for unlocking new technology.": "在这里，你可以购买升级来生成解锁新技术的研究点数。",
    "Here you can see a visual representation of technologies and what they provide.": "在这里，您可以看到技术的可视化表示及其提供的功能。",
    "Here you can unlock new technologies to improve your game, provided you have enough research points!": "在这里，您可以解锁新技术来改进您的游戏，前提是您有足够的研究点！",
    "HydroCarbons, Neutron Capture, Advanced Power Generation": "碳氢化合物，中子捕获，高级发电",
    "Knowledge Sharing": "知识分享",
    "Knowledge Sharing:": "知识分享:",
    "Hydrogen Fusion:": "氢聚变:",
    "Life Support Systems:": "生命维持系统:",
    "Open Science Lab:": "打开科学实验室:",
    "Open Science Club:": "打开科学俱乐部:",
    "Oxygen Fusion:": "氧聚变:",
    "Oxygen Fusion": "氧聚变",
    "Quantum Computing:": "量子计算:",
    "Science Kit:": "科学工具包:",
    "Quantum Computing": "量子计算",
    "Purchase a Science Kit to start generating Research points.": "购买一个科学工具包，开始生成研究点。",
    "Some text in the Modal..": "一些文本在模态框..",
    "The longest time anyone has gone without sleep is 11 days.": "最长的不睡觉时间是11天。",
    "This is a map of the known galaxy.": "这是一张已知星系的地图。",
    "undefined": "未知",
    "The most basic element known to man, very cheap to produce and has a pretty low value, but anything can be created from it.": "这是人类已知的最基本的元素，生产成本很低，价值也很低，但任何东西都可以用它来创造。",
    "Install a Hydrogen Refinery to maximize efficiency in Hydrogen generation - Power: 12KW / s": "安装一个氢气精炼厂，以最大限度地提高制氢效率-功率：12KW / 秒",
    "Add a Hydrogen Compressor to automate Hydrogen generation.": "增加一个氢气压缩机，以实现氢气的自动生成。",
    "Auto:": "自动:",
    "Compounds": "化合物",
    "Concepts - Early": "概念 - 早期",
    "Concepts - Mid": "概念 - 中期",
    "Concepts - Late": "概念 - 后期",
    "Concrete": "混凝土",
    "Diesel": "柴油",
    "A giraffe's neck contains the same number of vertebrae as a human's neck.": "长颈鹿脖子上的椎骨和人类脖子上的椎骨一样多。",
    "Add a Quantum Hydrogen Synthesizer for cutting-edge Hydrogen production - Power: 60KW / s": "添加一个量子氢合成器，用于尖端的氢生产-功率：60KW / 秒",
    "Add an Advanced Hydrogen Compressor for enhanced automation - Power: 3KW / s": "增加一个先进的氢压缩机，以增强自动化-功率：3KW / 秒",
    "Advanced Hydrogen Compressor:": "高级氢气压缩机:",
    "All Stock": "全部库存",
    "Fuse": "保险丝",
    "Cosmicopedia": "宇宙学",
    "Fleet Hangar": "舰队机库",
    "Here you can sell Hydrogen for cash": "在这里，你可以出售氢气换取现金",
    "Hydrogen Compressor:": "氢压缩机:",
    "Increase Storage": "增加存储",
    "Increase Storage:": "增加存储:",
    "Industrial Hydrogen Compressor:": "工业氢气压缩机：",
    "Manually gain one unit of Hydrogen.": "手动获得1单位的氢。",
    "Megastructures": "巨型结构",
    "Modal Header": "模态标题",
    "Neon": "氖",
    "Sell": "出售",
    "Sell Hydrogen:": "出售氢:",
    "Spica:": "说明:",
    "Stat 6:": "统计 6:",
    "Upgrade your Hydrogen storage capacity to hold more resources.": "升级你的储氢能力，以容纳更多的资源。",
    "Volcano Eruption!": "火山喷发!",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "N/A": "N/A",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Give $": "给予 $",
    "Quantity: ": "数量: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "Gases": "气体",
    "Metals": "金属",
    "Non Ferrous": "有色金属",
    "Silicates": "硅酸盐",
    "Metal Alloys": "金属合金",
    "HydroCarbons": "碳氢化合物",
    "% Stock": "% 库存",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Gain (.+) Research Points$/, '获得 $1 研究点'],
    [/^Gain (.+) Antimatter$/, '获得 $1 反物质'],
    [/^Gain (.+) Hydrogen:$/, '获得 $1 氢:'],
    [/^Add (.+) Hydrogen \/s$/, '增加 $1 氢 / 秒'],
    [/^Add (.+) Research \/s$/, '增加 $1 研究 / 秒'],
    [/^Add (.+) Asteroids$/, '增加 $1 小行星'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Minutes$/, '$1 分钟'],
    [/^([\d\.,]+) Research,$/, '$1 研究,'],
    [/^([\d\.,]+) Research$/, '$1 研究'],
    [/^([\d\.,]+) Hydrogen$/, '$1 氢'],
    [/^EXTRA ([\d\.,]+)$/, '额外 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);